name: "Build template and commit theme updates"

on:
  push

permissions:
  contents: write

jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Fetch the repository code"
        uses: "actions/checkout@v4"

      - name: "Update schemes"
        uses: "tinted-theming/tinted-builder-rust@latest"

      - name: "Commit the changes, if any"
        uses: "stefanzweifel/git-auto-commit-action@v5"
        with:
          commit_message: "chore: update with the latest colorschemes"
          commit_user_name: "tinted-theming-bot"
          commit_user_email: "tintedtheming@proton.me"
          commit_author: "tinted-theming-bot <tintedtheming@proton.me>"
